// takes a string and returns a hex color
export function avatarBackgroundColor(string: string) {
  let hash = 0;
  let i;

  /* eslint-disable no-bitwise */
  for (i = 0; i < string.length; i += 1) {
    hash = string.charCodeAt(i) + ((hash << 5) - hash);
  }

  let color = '#';

  for (i = 0; i < 3; i += 1) {
    const value = (hash >> (i * 8)) & 0xff;
    color += `00${value.toString(16)}`.slice(-2);
  }
  /* eslint-enable no-bitwise */

  return color;
}

// takes a string and returns a hex color which is darker than the color generated by the above funtion
export function avatarTextColor(hex: string, percent: number) {
  // Remove the # if present
  const color = hex.replace('#', '');

  // Parse r, g, b values
  const num = parseInt(color, 16);
  const r = (num >> 16) & 255;
  const g = (num >> 8) & 255;
  const b = num & 255;

  // Darken each component
  const newR = Math.floor(r * (1 - percent));
  const newG = Math.floor(g * (1 - percent));
  const newB = Math.floor(b * (1 - percent));

  // Convert back to hex
  return `#${((newR << 16) | (newG << 8) | newB).toString(16).padStart(6, '0')}`;
}

export function stringAvatar(name: string) {
  const backgroundColor = avatarBackgroundColor(name);
  const textColor = avatarTextColor(backgroundColor, 0.8);

  // Split name and filter out empty parts (e.g., from extra spaces)
  const nameParts = name.trim().split(' ').filter(Boolean);

  let initials = '';
  if (nameParts.length === 0) {
    initials = '?'; // fallback
  } else if (nameParts.length === 1) {
    initials = nameParts[0][0].toUpperCase();
  } else {
    initials = `${nameParts[0][0]}${nameParts[1][0]}`.toUpperCase();
  }

  return {
    sx: {
      bgcolor: backgroundColor,
      color: textColor,
      fontWeight: '800 !important',
      fontSize: '10px !important',
      height: '24px',
      width: '24px',
    },
    children: initials,
  };
}
