import { Theme } from '@mui/material';

export const styles = {
  root: (theme: Theme) => ({
    position: 'relative',
    display: 'block',
    width: '100%',
  }),
  label: (theme: Theme) => ({
    ...theme.typography.bodyMMedium,
    color: theme.palette.text.primary,
    display: 'block',
    marginBottom: theme.spacing(0.5),
    position: 'relative',
    width: '100%',
  }),
  inputWrapper: (theme: Theme) => ({
    display: 'flex',
    alignItems: 'center',
    padding: theme.spacing(1, 1.75),
    border: `1px solid ${theme.palette.grey[300]}`,
    borderRadius: theme.spacing(1),
    cursor: 'pointer',
    width: '100%',
    background: theme.palette.common.white,
    minHeight: 40,
    boxSizing: 'border-box',
    '&:hover': {
      borderColor: theme.palette.text.primary,
    },
  }),
  inputInner: (theme: Theme) => ({
    border: 'none',
    outline: 'none',
    flex: 1,
    fontSize: theme.typography.body2.fontSize,
    background: 'transparent',
    cursor: 'pointer',
    color: theme.palette.text.primary,
    '&::placeholder': {
      color: theme.palette.text.disabled,
    },
  }),
  inputIcon: (theme: Theme) => ({
    color: theme.palette.text.secondary,
    fontSize: 20,
    marginLeft: 1,
  }),
  popup: (theme: Theme) => ({
    position: 'absolute',
    top: `calc(100% + ${theme.spacing(0.75)})`,
    left: 0,
    zIndex: 100,
    background: theme.palette.common.white,
    borderRadius: theme.spacing(2),
    border: `1px solid ${theme.palette.grey[200]}`,
    padding: theme.spacing(2.5),
    width: 320,
    boxShadow: theme.shadows[8],
  }),
  popupPortal: (theme: Theme) => ({
    position: 'fixed',
    zIndex: 1300,
    background: theme.palette.common.white,
    borderRadius: theme.spacing(2),
    border: `1px solid ${theme.palette.grey[200]}`,
    padding: theme.spacing(2.5),
    width: 320,
    boxShadow: theme.shadows[8],
    [theme.breakpoints.down('sm')]: {
      width: `calc(100vw - ${theme.spacing(4)})`,
      maxWidth: 320,
      left: `${theme.spacing(2)} !important`,
      right: theme.spacing(2),
      padding: theme.spacing(2),
    },
  }),
  popupTitle: (theme: Theme) => ({
    fontSize: theme.typography.h5?.fontSize || 20,
    fontWeight: 700,
    color: theme.palette.grey[900],
    marginBottom: theme.spacing(1.5),
    [theme.breakpoints.down('sm')]: {
      fontSize: 16,
      marginBottom: theme.spacing(1),
    },
  }),
  topSection: (theme: Theme) => ({
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: theme.spacing(2.5),
    [theme.breakpoints.down('sm')]: {
      marginBottom: theme.spacing(1.5),
    },
  }),
  topSectionLeft: (theme: Theme) => ({
    display: 'flex',
    flexDirection: 'column',
  }),
  selects: (theme: Theme) => ({
    display: 'flex',
    gap: theme.spacing(0.75),
    [theme.breakpoints.down('sm')]: {
      flexWrap: 'wrap',
    },
  }),
  select: (theme: Theme) => ({
    border: 'none',
    backgroundColor: theme.palette.grey[100],
    borderRadius: theme.spacing(0.75),
    padding: theme.spacing(0.5, 1.5),
    fontSize: 14,
    fontWeight: 600,
    color: theme.palette.grey[800],
    cursor: 'pointer',
    outline: 'none',
    [theme.breakpoints.down('sm')]: {
      fontSize: 12,
      padding: theme.spacing(0.5, 1),
    },
  }),
  calendarIcon: (theme: Theme) => ({
    width: theme.spacing(8),
    height: theme.spacing(7),
    borderRadius: theme.spacing(1.5),
    background: theme.palette.primary.main,
    borderBottom: `4px solid ${theme.palette.primary.dark}`, // 3D effect
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    position: 'relative',
    marginTop: theme.spacing(0.5),
    [theme.breakpoints.down('sm')]: {
      width: theme.spacing(6),
      height: theme.spacing(5.5),
    },
  }),
  iconText: (theme: Theme) => ({
    fontSize: 28,
    fontWeight: 800,
    color: theme.palette.common.white,
    lineHeight: 1,
    [theme.breakpoints.down('sm')]: {
      fontSize: 20,
    },
  }),
  calendarRing: (theme: Theme) => ({
    position: 'absolute',
    top: -6,
    width: 8,
    height: 14,
    borderRadius: 4,
    background: theme.palette.common.white,
    border: `2.5px solid ${theme.palette.primary.main}`,
  }),
  ringLeft: { left: 14 },
  ringRight: { right: 14 },
  gridHead: (theme: Theme) => ({
    display: 'grid',
    gridTemplateColumns: 'repeat(7, 1fr)',
    textAlign: 'center',
    marginBottom: theme.spacing(0.5),
  }),
  gridHeadSpan: (theme: Theme) => ({
    fontSize: theme.typography.bodyXSRegular?.fontSize || 12,
    fontWeight: 700,
    color: theme.palette.grey[500],
    padding: theme.spacing(0.5, 0),
    textTransform: 'uppercase',
  }),
  gridHeadSun: (theme: Theme) => ({
    color: theme.palette.primary.main,
  }),
  grid: (theme: Theme) => ({
    display: 'grid',
    gridTemplateColumns: 'repeat(7, 1fr)',
    gap: theme.spacing(0.25),
  }),
  cell: (theme: Theme) => ({
    aspectRatio: '1',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: theme.typography.bodyXSRegular.fontSize,
    borderRadius: '50%',
    cursor: 'pointer',
    '&:hover': {
      background: theme.palette.grey[100],
    },
  }),
  empty: (theme: Theme) => ({
    color: theme.palette.grey[300],
    cursor: 'default',
  }),
  today: (theme: Theme) => ({
    color: theme.palette.primary.main,
    fontWeight: 600,
  }),
  selected: (theme: Theme) => ({
    color: theme.palette.primary.main,
    fontWeight: 700,
    borderBottom: `2px solid ${theme.palette.primary.main}`,
    borderRadius: 0, // override circle
    width: 'fit-content',
    padding: '0 4px',
    margin: 'auto',
    height: 24,
  }),
  sunday: (theme: Theme) => ({
    color: theme.palette.primary.main,
    fontWeight: 700,
  }),
  confirm: (theme: Theme) => ({
    width: '100%',
    marginTop: theme.spacing(2),
    padding: theme.spacing(1.25),
    border: 'none',
    borderRadius: theme.spacing(1.25),
    background: theme.palette.primary.main,
    color: theme.palette.common.white,
    fontSize: theme.typography.body2.fontSize,
    fontWeight: 500,
    cursor: 'pointer',
    '&:hover': {
      opacity: 0.88,
    },
  }),
  formHelperTextStyle: (theme: any) => ({
    display: 'flex',
    alignItems: 'center',
    gap: 0.5,
    marginTop: theme.spacing(0.5),
  }),
};
